version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
