language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

jobs:
  allow_failures:
  - rvm: ruby-head

install:
  - gem install bundler
  - bundle install

before_script:
  - bundle --version

script:
  - bundle exec rake test
